### ISSUE TITLE
Wrong naming 

### ISSUE THREAD

**Issue by PierreColombo** [WebNLG/GenerationEval#2]
Hello, 
Thanks a lot for your work. Just a minor detail 
submissions/rdf2text/en/DANGNT-SGU/human is named **human_eval_id_DANGNT-SGU.json** instead of **primary.json** .
Just for consistency for futur parsers :)
Cheers

**Comment by PierreColombo** [comment]
Similar pb with 'submissions/rdf2text/en/Huawei Noahs Ark Lab/automatic/' name  **primary.en.txt** instead of **primary.en** and ORANGE-NLG in submissions/rdf2text/en/ORANGE-NLG/automatic
and Facebook Conv ai
and OSU Neural NLG

**Comment by Shimorina** [comment]
We addressed your suggestions. Please see the new repo for the challenge results: https://github.com/WebNLG/challenge-2020
