### ISSUE TITLE
Human Evaluation on Russian

### ISSUE THREAD

**Issue by KaijuML** [WebNLG/GenerationEval#5]
Hi, 

I am interested in running correlations scores of automated metrics vs human judgements on the Russian data of Webnlg2020. What I ultimatly want is a way to get tuples of (source, [refs], prediction, {human_judgements}) so that I can:
 - Rerun correlations for existing metrics
 - Check correlations for new/experimental metrics I am currently working on

Sorry if there was an easy way to do this, but I could not find it. 

### What I tried

I am basing this issue on `main.ipynb` (if I am not mistaken, `webnlg_human_evaluation.ipynb` shares the same code):

First, please note that line11 of the first cell is incorrect, as there are no `data/human_evaluation/ratings/` folder (in any branch). I understand that intended behavior can be restored by using the current `data/human_evaluation/en_clean_v2/`.

However, if I switch to Russian (using `data/human_evaluation/ru_clean/`) then other files are not correct either: there are no `data_REF_ru.json` nor `ref2domain_ru.json` to be found. 

In order to create `data_REF_ru.json`, I would intuitively use `parser.py` on `data_REF_ru.xml`, is this correct? However, manually inspecting this latter file, I found that triplesets (original and modified) are in english. Should I then create the source by replacing english values by Russian values found in the mapping with `sameAs` ? Why is this not included already in `parser.py`?

If everything above is correct, Is it then also correct to match inputs/refs from  `data_REF_ru.xml` to human scores using what you called `sample_id` (line11 of second cell) from files in `data/human_evaluation/ru_clean/` and the `eid` property in `data/human_evaluation/data_REF_ru.xml` ?

Finally, and equally (if not more) importantly, where can I find the actual model outputs that were used to compute human scores / automated metric scores? As it stands, the repo seems to only contain 33 hyps/refs (`data/ru/`). If I understand [your paper](https://www.aclweb.org/anthology/2020.webnlg-1.7.pdf) correctly, there should be 110 * n_systems (Table 5). 

Thank you very much for your help,
Clément

**Comment by Shimorina** [comment]
Hi,

As far as I understood, your question was about the `humeval` branch (now deleted). Apologies, this branch is outdated and in fact abandoned.

We made public the official challenge repository (still under development) here: https://github.com/WebNLG/challenge-2020

Please take a look there, and reopen the issue if needed. I will close this for now.
